name: sigmus
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  intl: ^0.20.2
  provider: ^6.0.0
  flutter_svg: ^2.2.3
  chopper: ^8.5.0
  json_annotation: ^4.9.0
  drift: ^2.29.0
  drift_flutter: ^0.2.7
  sqlite3_flutter_libs: ^0.5.40
  path_provider: ^2.1.5
  google_fonts: ^6.2.1
  jwt_decode: ^0.3.1
  internet_connection_checker_plus: ^2.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  swagger_dart_code_generator: ^4.1.0
  build_runner: ^2.10.4
  drift_dev: ^2.29.0
  json_serializable: ^6.11.2
  chopper_generator: ^8.5.0

flutter:
  uses-material-design: true
  assets:
    - assets/sigmus.svg
    - lib/data/json/
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
